import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import { Space_Grotesk } from "next/font/google";

const customFont = localFont({
  src: '../../src/app/font/Satoshi-Variable.ttf',
  weight: '400',
  variable: "--font-satoshi", // Add CSS variable
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${spaceGrotesk.variable} ${customFont.variable} antialiased`}>
        {/* <TopHeader />
        <Header /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
